/**
 * Credit system config — shared between client and server. Pure constants,
 * no Node APIs, so it is safe to import from React components.
 *
 * PIXAI meters generation in credits. On localhost we charge per
 * image-producing API call (the expensive ones); text/vision QA calls are
 * free. Marketing per-asset prices (sprite=10, full character=60, …) are a
 * P2 reconciliation once real economics are measured.
 */

/** Reown AppKit project id (wallet connect). Env override for prod. */
export const REOWN_PROJECT_ID =
  process.env.NEXT_PUBLIC_REOWN_PROJECT_ID || '761c6637f8efd83cff05e5f759b51e3f'

/** SPL Token-2022 program id (our token is a Token-2022 mint, 6 decimals). */
export const TOKEN_2022_PROGRAM_ID = 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'

/**
 * $PIXAI token config. Driven by env so a single server command can flip
 * the whole app onto the real mint the moment it's launched — no code change.
 * Until NEXT_PUBLIC_TOKEN_MINT is set the app runs in test mode (dev faucet).
 *
 *   npm run set-token -- <MINT> <TREASURY> [network]
 */
export const TOKEN = {
  /** Token-2022 mint of $PIXAI. Empty until launched. */
  MINT: process.env.NEXT_PUBLIC_TOKEN_MINT || '',
  /** Token-2022 program (not legacy SPL-Token). */
  PROGRAM_ID: TOKEN_2022_PROGRAM_ID,
  /** 6 decimals. */
  DECIMALS: 6,
  /** Wallet that receives token payments for credits. */
  TREASURY: process.env.NEXT_PUBLIC_TOKEN_TREASURY || '',
  /** USD value of one whole token at launch (set via env). */
  USD_PRICE: Number(process.env.NEXT_PUBLIC_TOKEN_USD_PRICE || '0.001'),
  /** Credits granted per 1 whole token paid. */
  CREDITS_PER_TOKEN: 1,
  /** Network used for wallet + payments. */
  NETWORK: (process.env.NEXT_PUBLIC_SOLANA_NETWORK || 'solana-mainnet') as
    | 'solana-mainnet'
    | 'solana-devnet',
}

/** True once a real mint + treasury are configured (token is live). */
export function isTokenLive(): boolean {
  return Boolean(TOKEN.MINT && TOKEN.TREASURY)
}

/**
 * Pay in native SOL instead of the SPL token. Useful for demos / a simpler
 * payment rail (no burn — SOL just goes to the treasury). Set
 * NEXT_PUBLIC_PAY_IN_SOL=true to enable.
 */
export const PAY_IN_SOL = process.env.NEXT_PUBLIC_PAY_IN_SOL === 'true'

/** Wrapped-SOL mint — used to read the live SOL/USD price. */
export const WSOL_MINT = 'So11111111111111111111111111111111111111112'

/** Whether paid generation is active (either SOL mode or the SPL token). */
export function isPaymentLive(): boolean {
  // Native SOL needs a treasury (that's where it goes).
  if (PAY_IN_SOL) return Boolean(TOKEN.TREASURY)
  // SPL token: needs a mint. A treasury is only required when some of the
  // payment is NOT burned — at 100% burn nothing goes to a treasury.
  if (!TOKEN.MINT) return false
  return BURN_BPS >= 10000 || Boolean(TOKEN.TREASURY)
}

/**
 * Share of each generation payment that is BURNED (basis points; 10000 = 100%).
 * Default is 100% — every payment is destroyed. Tunable via env.
 */
export const BURN_BPS = Math.max(
  0,
  Math.min(10000, Number(process.env.NEXT_PUBLIC_BURN_BPS || '10000'))
)

/**
 * PRICING — every generation has a fixed price in USD. Balances are stored in
 * whole US cents (integer) so a prepaid balance never drifts with the token
 * price. You top up by sending $PIXAI (valued at the LIVE DexScreener price
 * at purchase time); each generation then costs its exact USD value.
 *
 * Tune these freely — they're retail prices (provider cost + margin).
 */
export const USD_COSTS = {
  /** Each image generated by /api/generate. (~$0.03 cost) */
  image: 0.05,
  /** Each outpaint step by /api/extend. */
  extend: 0.05,
  /** 3D model — representative flat; the 3D route overrides with estimate3DUsd. */
  model3d: 5,
  /** AI planning calls — scene brief, prop "art director" ideation. */
  brief: 0.01,
  /** AI vision QA passes — tile + sprite "art director" reviews. */
  review: 0.01,
} as const

export type CreditAction = keyof typeof USD_COSTS

/** Cents per dollar — the unit balances and costs are stored in. */
export const CENTS = 100
export const usdToCents = (usd: number) => Math.round(usd * CENTS)
export const centsToUsd = (cents: number) => cents / CENTS

/** Cost of an action in cents (integer). */
export function actionCostCents(action: CreditAction): number {
  return usdToCents(USD_COSTS[action])
}

/** Free trial granted to a fresh wallet, in cents ($0.20). */
export const SIGNUP_BONUS = usdToCents(0.2)

/** Dev faucet grant, in cents ($5). */
export const FAUCET_AMOUNT = usdToCents(5)

/**
 * 3D model pricing — charged in $PIXAI, scaled by prompt complexity.
 * A simple prompt lands near $2, a rich/rigged/multi-material one near $15.
 * (3D studio ships as a later update; this is the pricing it will use.)
 */
export const MODEL3D_USD = {
  MIN: Number(process.env.NEXT_PUBLIC_MODEL3D_USD_MIN || '2'),
  MAX: Number(process.env.NEXT_PUBLIC_MODEL3D_USD_MAX || '15'),
} as const

const COMPLEXITY_HINTS =
  /\b(rig|rigged|riggable|animat\w*|texture[ds]?|pbr|normal\s*map|detailed|intricate|ornate|multiple|several|scene|character|creature|armou?r|mechanical|robot|realistic|hi[- ]?poly|high[- ]?poly|sculpt\w*)\b/gi

/** Estimate the USD price of a 3D generation from its prompt ($2–$15). */
export function estimate3DUsd(prompt: string): number {
  const words = prompt.trim().split(/\s+/).filter(Boolean).length
  const hits = (prompt.match(COMPLEXITY_HINTS) || []).length
  const score = Math.min(1, (words / 45) * 0.6 + (hits / 6) * 0.4)
  const usd = MODEL3D_USD.MIN + score * (MODEL3D_USD.MAX - MODEL3D_USD.MIN)
  return Math.round(usd * 100) / 100
}

/** Convert a USD price to a token amount at a given live token price ($/token). */
export function usdToTokens(usd: number, tokenUsdPrice: number): number {
  if (!tokenUsdPrice || tokenUsdPrice <= 0) return 0
  return usd / tokenUsdPrice
}

// ─────────────────────────────────────────────────────────────────────────────
// MARKETPLACE — user-to-user 3D model sales, settled in native SOL.
//
// Independent of the generation payment rail above: a buyer pays the SELLER's
// wallet directly in SOL (peer-to-peer), with an optional platform fee skimmed
// to the treasury. This works even before the token launches. Prices are set by
// the seller directly in SOL (no live-price conversion needed).
// ─────────────────────────────────────────────────────────────────────────────

/** Lamports per whole SOL (1e9). Kept local so this stays import-free/client-safe. */
export const LAMPORTS_PER_SOL = 1_000_000_000

/** Listing currency — native SOL or the $PIXAI SPL token. */
export type MarketCurrency = 'sol' | 'token'

export const MARKET = {
  /**
   * Platform fee per sale, in basis points (10000 = 100%). The fee is sent to
   * MARKET.TREASURY; the rest goes straight to the seller. Default 0 (no fee) —
   * flip on later with NEXT_PUBLIC_MARKET_FEE_BPS, no code change.
   */
  FEE_BPS: Math.max(0, Math.min(10000, Number(process.env.NEXT_PUBLIC_MARKET_FEE_BPS || '0'))),
  /** Fee recipient — reuses the same treasury wallet as generation payments. */
  TREASURY: process.env.NEXT_PUBLIC_TOKEN_TREASURY || '',
  /** Minimum listing price in SOL (guards against dust / zero-price listings). */
  MIN_SOL: Number(process.env.NEXT_PUBLIC_MARKET_MIN_SOL || '0.001'),
  /** Maximum listing price in SOL (sanity cap on seller input). */
  MAX_SOL: Number(process.env.NEXT_PUBLIC_MARKET_MAX_SOL || '10000'),
} as const

export const solToLamports = (sol: number) => Math.round(sol * LAMPORTS_PER_SOL)
export const lamportsToSol = (lamports: number) => lamports / LAMPORTS_PER_SOL

/**
 * Surface the marketplace in the site nav. Off by default — the marketplace
 * ships DORMANT (reachable only at /marketplace) until we flip this on.
 * Set NEXT_PUBLIC_MARKET_NAV=true (e.g. on localhost) to reveal the nav tab.
 */
export const MARKET_NAV = process.env.NEXT_PUBLIC_MARKET_NAV === 'true'

/**
 * Split a total SOL price into the seller's share and the platform fee share,
 * both in lamports. Authoritative — server and client compute the same way.
 */
export function splitSale(priceSol: number, feeBps: number = MARKET.FEE_BPS): {
  total: number
  fee: number
  seller: number
} {
  const total = solToLamports(priceSol)
  const fee = Math.floor((total * Math.max(0, Math.min(10000, feeBps))) / 10000)
  return { total, fee, seller: total - fee }
}

/**
 * Split a price into seller + platform-fee shares in the SAME unit as the price
 * (whole SOL or whole tokens). Currency-agnostic — used for the $PIXAI rail and
 * for display. The client converts to lamports / base units when building the tx.
 */
export function feeShares(price: number, feeBps: number = MARKET.FEE_BPS): {
  fee: number
  seller: number
} {
  const fee = (price * Math.max(0, Math.min(10000, feeBps))) / 10000
  return { fee, seller: price - fee }
}

/** Marketplace can offer $PIXAI payment only when a token mint is configured. */
export function marketTokenEnabled(): boolean {
  return Boolean(TOKEN.MINT)
}

/** Marketing reference prices (per finished asset) — shown in UI, not charged. */
export const ASSET_PRICES: Record<string, number> = {
  '2D sprite + 8-frame animation': 10,
  'Tileset (16 tiles)': 25,
  'Parallax background (3 layers)': 20,
  'Full 2D character (all anims)': 60,
  '3D model + rig + animations': 100,
}
